apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: NAMESPACE
spec:
  type: ClusterIP
  selector:
    app: SERVICE_NAME
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
